name: marvel_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_bottom_navigation_bar: ^1.1.0
  any_link_preview: ^3.0.1
  cached_network_image: ^3.2.2
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  flash: ^3.0.5+1
  flutter_native_splash: ^2.2.10+1
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  http: ^1.1.0
  intl: ^0.18.1
  path: ^1.8.2
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#141414"
  image: "image/img.png"


flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
